stages:
  - build
  - deploy

create_nuget_package:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  before_script:       
    - 'echo "Incrementing the version number"'
    - NEW_VERSION=$(awk '/<Version>/ {print $1}' sync-files.csproj | sed 's/<Version>\(.*\)<\/Version>/\1/' | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
    - sed -i 's/<Version>.*<\/Version>/<Version>'"$NEW_VERSION"'<\/Version>/' YourProject.csproj
    - git config --global user.email "ben@click-on.co.uk"
    - git config --global user.name "Ben Robinson"
    - git commit -am "Increment version number to $NEW_VERSION"
    - git push origin HEAD:main
  script:
    - dotnet restore
    - dotnet build -c Release
    - dotnet pack -c Release -o ./nupkgs
  artifacts:
    paths:
      - ./nupkgs/*.nupkg
    expire_in: 1 hour
  tags:
    - local-docker
  only:
    - main

publish_nuget_package:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - 'echo "Uploading NuGet package to GitLab Package Registry"'    
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "nupkgs/*.nupkg" --source gitlab
  dependencies:
    - create_nuget_package
  only:
    - main
  tags:
    - local-docker

